#!/bin/sh

licensecheck --check '.*' --recursive --copyright --deb-machine --ignore '^(.*\.json|docs/assets/img/apple-icon-60x60\.png|debian/(changelog|copyright(_hints)?))$' --lines 0 -- * > debian/copyright_hints
